version: '3.8'

services:
  app:
    build: .
    container_name: gs2_app
    ports:
      - "5555:5555"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_DATABASE=postgres
      - DB_HOST=database
      - DB_PORT=5432
    depends_on:
      - database
    volumes:
      - .:/app
    networks:
      - gs2_network

  database:
    image: postgis/postgis
    container_name: gs2_database
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - gs2_db_data:/var/lib/postgresql/data
    networks:
      - gs2_network

volumes:
  gs2_db_data:

networks:
  gs2_network:
    driver: bridge
